services:
  mysql:
    image: mysql:8.0
    container_name: transport-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transport_db
      MYSQL_USER: transport_user
      MYSQL_PASSWORD: transport_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - transport-network

volumes:
  mysql_data:

networks:
  transport-network:
    driver: bridge