server:
  port: 8084

spring:
  application:
    name: tracking-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/smartshipd
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
