export const customers = [
    {
        id: 1,
        userId: 101,
        firstName: 'Nguyễn',
        lastName: 'Văn An',
        email: 'an.nguyen@company.com',
        phone: '0901234567',
        companyName: 'Công ty TNHH ABC',
        taxCode: '0123456789',
        createdAt: '2025-01-15T08:30:00',
        updatedAt: '2025-03-20T14:45:00',
        addresses: [
            {
                id: 1,
                addressLine1: '123 Nguyễn Văn Linh',
                addressLine2: 'Phường Tân Phong',
                city: 'TP.HCM',
                state: '',
                postalCode: '70000',
                country: 'Việt Nam',
                isDefault: true,
                addressType: 'BOTH',
                latitude: 10.7769,
                longitude: 106.7009,
            },
        ],
        orderCount: 15,
        totalSpent: 25000000,
    },
    {
        id: 2,
        userId: 102,
        firstName: 'Nguyễn',
        lastName: 'Văn A',
        email: 'nguyenvana@email.com',
        phone: '0912345678',
        companyName: '',
        taxCode: '',
        createdAt: '2025-02-10T10:15:00',
        updatedAt: '2025-04-15T09:30:00',
        addresses: [
            {
                id: 2,
                addressLine1: '456 Lê Văn Lương',
                addressLine2: 'Phường 1',
                city: 'TP.HCM',
                state: '',
                postalCode: '70000',
                country: 'Việt Nam',
                isDefault: true,
                addressType: 'BOTH',
                latitude: 10.7568,
                longitude: 106.7013,
            },
        ],
        orderCount: 3,
        totalSpent: 2500000,
    },
    {
        id: 3,
        userId: 103,
        firstName: 'Trần',
        lastName: 'Thị B',
        email: 'tranthib@email.com',
        phone: '0923456789',
        companyName: '',
        taxCode: '',
        createdAt: '2025-02-15T14:20:00',
        updatedAt: '2025-03-25T11:40:00',
        addresses: [
            {
                id: 3,
                addressLine1: '789 Điện Biên Phủ',
                addressLine2: 'Phường 15',
                city: 'TP.HCM',
                state: '',
                postalCode: '70000',
                country: 'Việt Nam',
                isDefault: true,
                addressType: 'SHIPPING',
                latitude: 10.7991,
                longitude: 106.6926,
            },
            {
                id: 4,
                addressLine1: '45 Lý Tự Trọng',
                addressLine2: 'Phường Bến Nghé',
                city: 'TP.HCM',
                state: '',
                postalCode: '70000',
                country: 'Việt Nam',
                isDefault: false,
                addressType: 'BILLING',
                latitude: 10.7765,
                longitude: 106.7019,
            },
        ],
        orderCount: 7,
        totalSpent: 8500000,
    },
    {
        id: 4,
        userId: 104,
        firstName: 'Lê',
        lastName: 'Văn C',
        email: 'levanc@email.com',
        phone: '0934567890',
        companyName: 'Công ty XYZ',
        taxCode: '9876543210',
        createdAt: '2025-03-05T09:10:00',
        updatedAt: '2025-04-10T16:30:00',
        addresses: [
            {
                id: 5,
                addressLine1: '101 Hai Bà Trưng',
                addressLine2: 'Phường Bến Nghé',
                city: 'TP.HCM',
                state: '',
                postalCode: '70000',
                country: 'Việt Nam',
                isDefault: true,
                addressType: 'BOTH',
                latitude: 10.7731,
                longitude: 106.7029,
            },
        ],
        orderCount: 10,
        totalSpent: 15000000,
    },
    {
        id: 5,
        userId: 105,
        firstName: 'Phạm',
        lastName: 'Thị D',
        email: 'phamthid@email.com',
        phone: '0945678901',
        companyName: '',
        taxCode: '',
        createdAt: '2025-03-20T11:25:00',
        updatedAt: '2025-04-18T10:15:00',
        addresses: [
            {
                id: 6,
                addressLine1: '202 Nguyễn Hữu Cảnh',
                addressLine2: 'Phường 22',
                city: 'TP.HCM',
                state: '',
                postalCode: '70000',
                country: 'Việt Nam',
                isDefault: true,
                addressType: 'BOTH',
                latitude: 10.7868,
                longitude: 106.7113,
            },
        ],
        orderCount: 2,
        totalSpent: 1800000,
    },
];

export default customers;