export const warehouses = [
    {
        id: 1,
        name: 'Kho Quận 7',
        address: '123 Nguyễn Văn Linh, Phường Tân Phong',
        city: 'TP.HCM',
        state: '',
        postalCode: '70000',
        country: 'Việt Nam',
        latitude: 10.7269,
        longitude: 106.7219,
        status: 'ACTIVE',
        managerId: 301,
        managerName: 'Lê Văn Quản',
        totalProducts: 245,
        totalValue: 1250000000,
    },
    {
        id: 2,
        name: 'Kho Quận 2',
        address: '456 Mai Chí Thọ, Phường An Phú',
        city: 'TP.HCM',
        state: '',
        postalCode: '70000',
        country: 'Việt Nam',
        latitude: 10.7859,
        longitude: 106.7512,
        status: 'ACTIVE',
        managerId: 302,
        managerName: 'Trần Thị Kho',
        totalProducts: 189,
        totalValue: 980000000,
    },
    {
        id: 3,
        name: 'Kho Quận 9',
        address: '789 Lê Văn Việt, Phường Hiệp Phú',
        city: 'TP.HCM',
        state: '',
        postalCode: '70000',
        country: 'Việt Nam',
        latitude: 10.8456,
        longitude: 106.7798,
        status: 'ACTIVE',
        managerId: 303,
        managerName: 'Nguyễn Văn Kho',
        totalProducts: 312,
        totalValue: 1560000000,
    },
    {
        id: 4,
        name: 'Kho Bình Dương',
        address: '101 Đại lộ Bình Dương, Thành phố Thủ Dầu Một',
        city: 'Bình Dương',
        state: '',
        postalCode: '75000',
        country: 'Việt Nam',
        latitude: 10.9804,
        longitude: 106.6521,
        status: 'ACTIVE',
        managerId: 304,
        managerName: 'Phạm Thị Quản',
        totalProducts: 278,
        totalValue: 1320000000,
    },
    {
        id: 5,
        name: 'Kho Đồng Nai',
        address: '202 Phạm Văn Thuận, Biên Hòa',
        city: 'Đồng Nai',
        state: '',
        postalCode: '76000',
        country: 'Việt Nam',
        latitude: 10.9559,
        longitude: 106.8416,
        status: 'MAINTENANCE',
        managerId: 305,
        managerName: 'Hoàng Văn Kho',
        totalProducts: 156,
        totalValue: 750000000,
    },
];

export const products = [
    {
        id: 101,
        sku: 'LT-DELL-XPS13',
        name: 'Laptop Dell XPS 13',
        description: 'Laptop cao cấp Dell XPS 13 với màn hình 13.4 inch, CPU Intel Core i7, RAM 16GB',
        category: 'Laptop',
        weight: 1.2,
        dimensions: '30x20x1.5',
        unitPrice: 2350000,
        createdAt: '2024-12-01T08:00:00',
        updatedAt: '2025-03-15T10:30:00',
        image: 'https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/xps-13-9315/media-gallery/blue/laptop-xps-13-9315-blue-gallery-4.psd?fmt=png-alpha&pscan=auto&scl=1&hei=402&wid=402&qlt=100,1&resMode=sharp2&size=402,402&chrss=full',
        totalStock: 45,
    },
    {
        id: 102,
        sku: 'SP-SAMSUNG-S23',
        name: 'Điện thoại Samsung Galaxy S23',
        description: 'Điện thoại Samsung Galaxy S23 với màn hình 6.1 inch, chip Snapdragon 8 Gen 2, RAM 8GB',
        category: 'Điện thoại',
        weight: 0.168,
        dimensions: '14.6x7.0x0.8',
        unitPrice: 700000,
        createdAt: '2025-01-10T09:15:00',
        updatedAt: '2025-03-20T11:45:00',
        image: 'https://images.samsung.com/is/image/samsung/p6pim/vn/2302/gallery/vn-galaxy-s23-s911-sm-s911bzgcxxv-534848082?$650_519_PNG$',
        totalStock: 78,
    },
    {
        id: 103,
        sku: 'HP-SONY-WH1000XM5',
        name: 'Tai nghe Sony WH-1000XM5',
        description: 'Tai nghe chống ồn cao cấp Sony WH-1000XM5 với thời lượng pin 30 giờ',
        category: 'Tai nghe',
        weight: 0.25,
        dimensions: '20x17x5',
        unitPrice: 1120000,
        createdAt: '2025-01-15T10:30:00',
        updatedAt: '2025-03-25T14:20:00',
        image: 'https://www.sony.com.vn/image/5d02da5df552836db894cead8a68f5f3?fmt=pjpeg&wid=330&bgcolor=FFFFFF&bgc=FFFFFF',
        totalStock: 32,
    },
    {
        id: 104,
        sku: 'TB-APPLE-IPADPRO11',
        name: 'iPad Pro 11"',
        description: 'iPad Pro 11 inch với chip M2, màn hình Liquid Retina, 256GB',
        category: 'Máy tính bảng',
        weight: 0.47,
        dimensions: '24.7x17.8x0.6',
        unitPrice: 3400000,
        createdAt: '2025-02-01T08:45:00',
        updatedAt: '2025-04-01T09:30:00',
        image: 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/ipad-pro-model-select-gallery-1-202210?wid=5120&hei=2880&fmt=p-jpg&qlt=95&.v=1664411207449',
        totalStock: 25,
    },
    {
        id: 105,
        sku: 'SP-JBL-CHARGE5',
        name: 'Loa Bluetooth JBL Charge 5',
        description: 'Loa Bluetooth JBL Charge 5 chống nước, thời lượng pin 20 giờ',
        category: 'Loa',
        weight: 0.96,
        dimensions: '22x9.5x9.5',
        unitPrice: 790000,
        createdAt: '2025-02-15T11:20:00',
        updatedAt: '2025-04-05T13:15:00',
        image: 'https://www.jbl.com/dw/image/v2/BFND_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw9a1ef764/JBL_Charge_5_Blue_Hero_1605x1605px.png?sw=535&sh=535',
        totalStock: 50,
    },
];

export const inventory = [
    {
        id: 1,
        warehouseId: 1,
        warehouseName: 'Kho Quận 7',
        productId: 101,
        productName: 'Laptop Dell XPS 13',
        quantity: 15,
        minStockLevel: 5,
        maxStockLevel: 30,
        lastRestockDate: '2025-04-10',
        status: 'NORMAL',
    },
    {
        id: 2,
        warehouseId: 1,
        warehouseName: 'Kho Quận 7',
        productId: 102,
        productName: 'Điện thoại Samsung Galaxy S23',
        quantity: 25,
        minStockLevel: 10,
        maxStockLevel: 50,
        lastRestockDate: '2025-04-15',
        status: 'NORMAL',
    },
    {
        id: 3,
        warehouseId: 2,
        warehouseName: 'Kho Quận 2',
        productId: 101,
        productName: 'Laptop Dell XPS 13',
        quantity: 10,
        minStockLevel: 5,
        maxStockLevel: 25,
        lastRestockDate: '2025-04-05',
        status: 'NORMAL',
    },
    {
        id: 4,
        warehouseId: 2,
        warehouseName: 'Kho Quận 2',
        productId: 103,
        productName: 'Tai nghe Sony WH-1000XM5',
        quantity: 12,
        minStockLevel: 8,
        maxStockLevel: 30,
        lastRestockDate: '2025-04-12',
        status: 'NORMAL',
    },
    {
        id: 5,
        warehouseId: 3,
        warehouseName: 'Kho Quận 9',
        productId: 104,
        productName: 'iPad Pro 11"',
        quantity: 8,
        minStockLevel: 5,
        maxStockLevel: 20,
        lastRestockDate: '2025-04-08',
        status: 'NORMAL',
    },
    {
        id: 6,
        warehouseId: 3,
        warehouseName: 'Kho Quận 9',
        productId: 105,
        productName: 'Loa Bluetooth JBL Charge 5',
        quantity: 20,
        minStockLevel: 10,
        maxStockLevel: 40,
        lastRestockDate: '2025-04-18',
        status: 'NORMAL',
    },
    {
        id: 7,
        warehouseId: 4,
        warehouseName: 'Kho Bình Dương',
        productId: 102,
        productName: 'Điện thoại Samsung Galaxy S23',
        quantity: 30,
        minStockLevel: 15,
        maxStockLevel: 60,
        lastRestockDate: '2025-04-14',
        status: 'NORMAL',
    },
    {
        id: 8,
        warehouseId: 4,
        warehouseName: 'Kho Bình Dương',
        productId: 103,
        productName: 'Tai nghe Sony WH-1000XM5',
        quantity: 15,
        minStockLevel: 8,
        maxStockLevel: 30,
        lastRestockDate: '2025-04-16',
        status: 'NORMAL',
    },
    {
        id: 9,
        warehouseId: 5,
        warehouseName: 'Kho Đồng Nai',
        productId: 101,
        productName: 'Laptop Dell XPS 13',
        quantity: 20,
        minStockLevel: 10,
        maxStockLevel: 40,
        lastRestockDate: '2025-04-02',
        status: 'NORMAL',
    },
    {
        id: 10,
        warehouseId: 5,
        warehouseName: 'Kho Đồng Nai',
        productId: 105,
        productName: 'Loa Bluetooth JBL Charge 5',
        quantity: 30,
        minStockLevel: 15,
        maxStockLevel: 50,
        lastRestockDate: '2025-04-09',
        status: 'NORMAL',
    },
];

export const inventoryTransactions = [
    {
        id: 1,
        inventoryId: 1,
        warehouseId: 1,
        productId: 101,
        transactionType: 'INBOUND',
        quantity: 10,
        referenceId: 'PO-2025-0001',
        referenceType: 'PURCHASE_ORDER',
        notes: 'Nhập kho từ nhà cung cấp ABC',
        createdBy: 'Lê Văn Quản',
        createdAt: '2025-04-10T09:30:00',
    },
    {
        id: 2,
        inventoryId: 2,
        warehouseId: 1,
        productId: 102,
        transactionType: 'INBOUND',
        quantity: 15,
        referenceId: 'PO-2025-0002',
        referenceType: 'PURCHASE_ORDER',
        notes: 'Nhập kho từ nhà cung cấp XYZ',
        createdBy: 'Lê Văn Quản',
        createdAt: '2025-04-15T10:15:00',
    },
    {
        id: 3,
        inventoryId: 1,
        warehouseId: 1,
        productId: 101,
        transactionType: 'OUTBOUND',
        quantity: 2,
        referenceId: 'ORD-2025-0001',
        referenceType: 'ORDER',
        notes: 'Xuất kho cho đơn hàng',
        createdBy: 'Lê Văn Quản',
        createdAt: '2025-04-20T14:45:00',
    },
    {
        id: 4,
        inventoryId: 3,
        warehouseId: 2,
        productId: 101,
        transactionType: 'TRANSFER',
        quantity: 5,
        referenceId: 'TR-2025-0001',
        referenceType: 'TRANSFER',
        notes: 'Chuyển kho từ Kho Quận 7',
        createdBy: 'Trần Thị Kho',
        createdAt: '2025-04-05T11:20:00',
    },
    {
        id: 5,
        inventoryId: 5,
        warehouseId: 3,
        productId: 104,
        transactionType: 'INBOUND',
        quantity: 8,
        referenceId: 'PO-2025-0003',
        referenceType: 'PURCHASE_ORDER',
        notes: 'Nhập kho từ nhà cung cấp Apple',
        createdBy: 'Nguyễn Văn Kho',
        createdAt: '2025-04-08T08:45:00',
    },
];

export default {
    warehouses,
    products,
    inventory,
    inventoryTransactions,
};