export const orders = [
    {
        id: 1,
        orderNumber: 'ORD-2025-0001',
        customerId: 1,
        customerName: 'Công ty TNHH ABC',
        status: 'DELIVERED',
        shippingAddress: '123 Nguyễn Văn Linh, Quận 7, TP.HCM',
        billingAddress: '123 Nguyễn Văn Linh, Quận 7, TP.HCM',
        shippingFee: 150000,
        totalAmount: 2500000,
        paymentMethod: 'BANK_TRANSFER',
        paymentStatus: 'PAID',
        notes: 'Giao hàng giờ hành chính',
        createdAt: '2025-04-20T08:30:00',
        expectedDeliveryDate: '2025-04-22',
        actualDeliveryDate: '2025-04-22',
        items: [
            {
                id: 1,
                productId: 101,
                productName: 'Laptop Dell XPS 13',
                quantity: 1,
                unitPrice: 2350000,
                totalPrice: 2350000,
            },
        ],
        tracking: [
            {
                id: 1,
                status: 'ORDER_PLACED',
                location: 'Hệ thống',
                timestamp: '2025-04-20T08:30:00',
                notes: 'Đơn hàng đã được tạo',
            },
            {
                id: 2,
                status: 'PROCESSING',
                location: 'Kho Quận 7',
                timestamp: '2025-04-20T10:15:00',
                notes: 'Đơn hàng đang được xử lý',
            },
            {
                id: 3,
                status: 'PICKED_UP',
                location: 'Kho Quận 7',
                timestamp: '2025-04-21T08:00:00',
                notes: 'Đơn hàng đã được lấy từ kho',
            },
            {
                id: 4,
                status: 'IN_TRANSIT',
                location: 'Trung tâm phân phối',
                timestamp: '2025-04-21T10:30:00',
                notes: 'Đơn hàng đang trên đường giao',
            },
            {
                id: 5,
                status: 'OUT_FOR_DELIVERY',
                location: 'TP.HCM',
                timestamp: '2025-04-22T08:15:00',
                notes: 'Đơn hàng đang được giao',
            },
            {
                id: 6,
                status: 'DELIVERED',
                location: '123 Nguyễn Văn Linh, Quận 7, TP.HCM',
                timestamp: '2025-04-22T14:20:00',
                notes: 'Đơn hàng đã được giao thành công',
            },
        ],
    },
    {
        id: 2,
        orderNumber: 'ORD-2025-0002',
        customerId: 2,
        customerName: 'Nguyễn Văn A',
        status: 'IN_TRANSIT',
        shippingAddress: '456 Lê Văn Lương, Quận 4, TP.HCM',
        billingAddress: '456 Lê Văn Lương, Quận 4, TP.HCM',
        shippingFee: 50000,
        totalAmount: 750000,
        paymentMethod: 'COD',
        paymentStatus: 'PENDING',
        notes: 'Gọi trước khi giao',
        createdAt: '2025-04-21T14:45:00',
        expectedDeliveryDate: '2025-04-24',
        actualDeliveryDate: null,
        items: [
            {
                id: 2,
                productId: 102,
                productName: 'Điện thoại Samsung Galaxy S23',
                quantity: 1,
                unitPrice: 700000,
                totalPrice: 700000,
            },
        ],
        tracking: [
            {
                id: 7,
                status: 'ORDER_PLACED',
                location: 'Hệ thống',
                timestamp: '2025-04-21T14:45:00',
                notes: 'Đơn hàng đã được tạo',
            },
            {
                id: 8,
                status: 'PROCESSING',
                location: 'Kho Quận 2',
                timestamp: '2025-04-22T09:30:00',
                notes: 'Đơn hàng đang được xử lý',
            },
            {
                id: 9,
                status: 'PICKED_UP',
                location: 'Kho Quận 2',
                timestamp: '2025-04-23T08:45:00',
                notes: 'Đơn hàng đã được lấy từ kho',
            },
            {
                id: 10,
                status: 'IN_TRANSIT',
                location: 'Trung tâm phân phối',
                timestamp: '2025-04-23T11:20:00',
                notes: 'Đơn hàng đang trên đường giao',
            },
        ],
    },
    {
        id: 3,
        orderNumber: 'ORD-2025-0003',
        customerId: 3,
        customerName: 'Trần Thị B',
        status: 'PENDING',
        shippingAddress: '789 Điện Biên Phủ, Quận 3, TP.HCM',
        billingAddress: '789 Điện Biên Phủ, Quận 3, TP.HCM',
        shippingFee: 80000,
        totalAmount: 1200000,
        paymentMethod: 'CREDIT_CARD',
        paymentStatus: 'PAID',
        notes: '',
        createdAt: '2025-04-23T11:20:00',
        expectedDeliveryDate: '2025-04-26',
        actualDeliveryDate: null,
        items: [
            {
                id: 3,
                productId: 103,
                productName: 'Tai nghe Sony WH-1000XM5',
                quantity: 1,
                unitPrice: 1120000,
                totalPrice: 1120000,
            },
        ],
        tracking: [
            {
                id: 11,
                status: 'ORDER_PLACED',
                location: 'Hệ thống',
                timestamp: '2025-04-23T11:20:00',
                notes: 'Đơn hàng đã được tạo',
            },
        ],
    },
    {
        id: 4,
        orderNumber: 'ORD-2025-0004',
        customerId: 4,
        customerName: 'Lê Văn C',
        status: 'PROCESSING',
        shippingAddress: '101 Hai Bà Trưng, Quận 1, TP.HCM',
        billingAddress: '101 Hai Bà Trưng, Quận 1, TP.HCM',
        shippingFee: 100000,
        totalAmount: 3500000,
        paymentMethod: 'DIGITAL_WALLET',
        paymentStatus: 'PAID',
        notes: 'Giao hàng vào cuối tuần',
        createdAt: '2025-04-22T16:10:00',
        expectedDeliveryDate: '2025-04-25',
        actualDeliveryDate: null,
        items: [
            {
                id: 4,
                productId: 104,
                productName: 'iPad Pro 11"',
                quantity: 1,
                unitPrice: 3400000,
                totalPrice: 3400000,
            },
        ],
        tracking: [
            {
                id: 12,
                status: 'ORDER_PLACED',
                location: 'Hệ thống',
                timestamp: '2025-04-22T16:10:00',
                notes: 'Đơn hàng đã được tạo',
            },
            {
                id: 13,
                status: 'PROCESSING',
                location: 'Kho Quận 9',
                timestamp: '2025-04-23T10:45:00',
                notes: 'Đơn hàng đang được xử lý',
            },
        ],
    },
    {
        id: 5,
        orderNumber: 'ORD-2025-0005',
        customerId: 5,
        customerName: 'Phạm Thị D',
        status: 'CANCELLED',
        shippingAddress: '202 Nguyễn Hữu Cảnh, Quận Bình Thạnh, TP.HCM',
        billingAddress: '202 Nguyễn Hữu Cảnh, Quận Bình Thạnh, TP.HCM',
        shippingFee: 60000,
        totalAmount: 850000,
        paymentMethod: 'BANK_TRANSFER',
        paymentStatus: 'REFUNDED',
        notes: 'Khách hàng hủy đơn',
        createdAt: '2025-04-19T09:30:00',
        expectedDeliveryDate: '2025-04-22',
        actualDeliveryDate: null,
        items: [
            {
                id: 5,
                productId: 105,
                productName: 'Loa Bluetooth JBL Charge 5',
                quantity: 1,
                unitPrice: 790000,
                totalPrice: 790000,
            },
        ],
        tracking: [
            {
                id: 14,
                status: 'ORDER_PLACED',
                location: 'Hệ thống',
                timestamp: '2025-04-19T09:30:00',
                notes: 'Đơn hàng đã được tạo',
            },
            {
                id: 15,
                status: 'PROCESSING',
                location: 'Kho Quận 7',
                timestamp: '2025-04-19T14:20:00',
                notes: 'Đơn hàng đang được xử lý',
            },
            {
                id: 16,
                status: 'CANCELLED',
                location: 'Hệ thống',
                timestamp: '2025-04-20T10:15:00',
                notes: 'Đơn hàng đã bị hủy theo yêu cầu của khách hàng',
            },
        ],
    },
];

export default orders;