export const routes = [
    {
        id: 1,
        name: 'Route #R2025-0045',
        startLocationId: 1,
        startLocationName: 'Kho Quận 7',
        endLocationId: null,
        endLocationName: 'Quận 1, TP.HCM',
        estimatedDistance: 12.5,
        estimatedDuration: 45,
        status: 'IN_PROGRESS',
        createdAt: '2025-04-23T17:30:00',
        scheduledDate: '2025-04-24',
        driverId: 1,
        driverName: 'Hoàng Minh Tuấn',
        vehicleId: 1,
        vehiclePlate: '51F-12345',
        stops: [
            {
                id: 1,
                routeId: 1,
                orderId: 1,
                orderNumber: 'ORD-2025-0001',
                stopNumber: 1,
                address: '123 Nguyễn Văn Linh, Quận 7, TP.HCM',
                latitude: 10.7269,
                longitude: 106.7219,
                estimatedArrivalTime: '2025-04-24T08:30:00',
                actualArrivalTime: '2025-04-24T08:25:00',
                status: 'COMPLETED',
                notes: 'Đã giao hàng thành công',
            },
            {
                id: 2,
                routeId: 1,
                orderId: 2,
                orderNumber: 'ORD-2025-0002',
                stopNumber: 2,
                address: '456 Lê Văn Lương, Quận 4, TP.HCM',
                latitude: 10.7568,
                longitude: 106.7013,
                estimatedArrivalTime: '2025-04-24T09:15:00',
                actualArrivalTime: '2025-04-24T09:10:00',
                status: 'COMPLETED',
                notes: 'Đã giao hàng thành công',
            },
            {
                id: 3,
                routeId: 1,
                orderId: 3,
                orderNumber: 'ORD-2025-0003',
                stopNumber: 3,
                address: '789 Điện Biên Phủ, Quận 3, TP.HCM',
                latitude: 10.7991,
                longitude: 106.6926,
                estimatedArrivalTime: '2025-04-24T10:00:00',
                actualArrivalTime: '2025-04-24T09:55:00',
                status: 'COMPLETED',
                notes: 'Đã giao hàng thành công',
            },
            {
                id: 4,
                routeId: 1,
                orderId: 4,
                orderNumber: 'ORD-2025-0004',
                stopNumber: 4,
                address: '101 Hai Bà Trưng, Quận 1, TP.HCM',
                latitude: 10.7731,
                longitude: 106.7029,
                estimatedArrivalTime: '2025-04-24T10:45:00',
                actualArrivalTime: null,
                status: 'PENDING',
                notes: '',
            },
            {
                id: 5,
                routeId: 1,
                orderId: 6,
                orderNumber: 'ORD-2025-0006',
                stopNumber: 5,
                address: '202 Lý Tự Trọng, Quận 1, TP.HCM',
                latitude: 10.7765,
                longitude: 106.7019,
                estimatedArrivalTime: '2025-04-24T11:30:00',
                actualArrivalTime: null,
                status: 'PENDING',
                notes: '',
            },
        ],
    },
    {
        id: 2,
        name: 'Route #R2025-0046',
        startLocationId: 3,
        startLocationName: 'Kho Quận 9',
        endLocationId: null,
        endLocationName: 'Quận 2, TP.HCM',
        estimatedDistance: 18.2,
        estimatedDuration: 60,
        status: 'IN_PROGRESS',
        createdAt: '2025-04-23T17:45:00',
        scheduledDate: '2025-04-24',
        driverId: 2,
        driverName: 'Nguyễn Thanh Bình',
        vehicleId: 2,
        vehiclePlate: '51F-23456',
        stops: [
            {
                id: 6,
                routeId: 2,
                orderId: 7,
                orderNumber: 'ORD-2025-0007',
                stopNumber: 1,
                address: '123 Đường D2, Quận 9, TP.HCM',
                latitude: 10.8456,
                longitude: 106.7798,
                estimatedArrivalTime: '2025-04-24T08:30:00',
                actualArrivalTime: '2025-04-24T08:35:00',
                status: 'COMPLETED',
                notes: 'Đã giao hàng thành công',
            },
            {
                id: 7,
                routeId: 2,
                orderId: 8,
                orderNumber: 'ORD-2025-0008',
                stopNumber: 2,
                address: '456 Đỗ Xuân Hợp, Quận 9, TP.HCM',
                latitude: 10.8356,
                longitude: 106.7698,
                estimatedArrivalTime: '2025-04-24T09:15:00',
                actualArrivalTime: '2025-04-24T09:20:00',
                status: 'COMPLETED',
                notes: 'Đã giao hàng thành công',
            },
            {
                id: 8,
                routeId: 2,
                orderId: 9,
                orderNumber: 'ORD-2025-0009',
                stopNumber: 3,
                address: '789 Đường Liên Phường, Quận 9, TP.HCM',
                latitude: 10.8256,
                longitude: 106.7598,
                estimatedArrivalTime: '2025-04-24T10:00:00',
                actualArrivalTime: null,
                status: 'PENDING',
                notes: '',
            },
            {
                id: 9,
                routeId: 2,
                orderId: 10,
                orderNumber: 'ORD-2025-0010',
                stopNumber: 4,
                address: '101 Mai Chí Thọ, Quận 2, TP.HCM',
                latitude: 10.7859,
                longitude: 106.7512,
                estimatedArrivalTime: '2025-04-24T10:45:00',
                actualArrivalTime: null,
                status: 'PENDING',
                notes: '',
            },
            {
                id: 10,
                routeId: 2,
                orderId: 11,
                orderNumber: 'ORD-2025-0011',
                stopNumber: 5,
                address: '202 Nguyễn Thị Định, Quận 2, TP.HCM',
                latitude: 10.7959,
                longitude: 106.7612,
                estimatedArrivalTime: '2025-04-24T11:30:00',
                actualArrivalTime: null,
                status: 'PENDING',
                notes: '',
            },
            {
                id: 11,
                routeId: 2,
                orderId: 12,
                orderNumber: 'ORD-2025-0012',
                stopNumber: 6,
                address: '303 Lương Định Của, Quận 2, TP.HCM',
                latitude: 10.7759,
                longitude: 106.7412,
                estimatedArrivalTime: '2025-04-24T12:15:00',
                actualArrivalTime: null,
                status: 'PENDING',
                notes: '',
            },
            {
                id: 12,
                routeId: 2,
                orderId: 13,
                orderNumber: 'ORD-2025-0013',
                stopNumber: 7,
                address: '404 Trần Não, Quận 2, TP.HCM',
                latitude: 10.7659,
                longitude: 106.7312,
                estimatedArrivalTime: '2025-04-24T13:00:00',
                actualArrivalTime: null,
                status: 'PENDING',
                notes: '',
            },
        ],
    },
    {
        id: 3,
        name: 'Route #R2025-0047',
        startLocationId: 2,
        startLocationName: 'Kho Quận 2',
        endLocationId: null,
        endLocationName: 'Quận Bình Thạnh, TP.HCM',
        estimatedDistance: 15.3,
        estimatedDuration: 55,
        status: 'PLANNED',
        createdAt: '2025-04-23T18:00:00',
        scheduledDate: '2025-04-25',
        driverId: 4,
        driverName: 'Lê Thị Hương',
        vehicleId: 4,
        vehiclePlate: '51F-45678',
        stops: [
            {
                id: 13,
                routeId: 3,
                orderId: 14,
                orderNumber: 'ORD-2025-0014',
                stopNumber: 1,
                address: '123 Xô Viết Nghệ Tĩnh, Quận Bình Thạnh, TP.HCM',
                latitude: 10.8068,
                longitude: 106.7113,
                estimatedArrivalTime: '2025-04-25T08:30:00',
                actualArrivalTime: null,
                status: 'PENDING',
                notes: '',
            },
            {
                id: 14,
                routeId: 3,
                orderId: 15,
                orderNumber: 'ORD-2025-0015',
                stopNumber: 2,
                address: '456 Phan Văn Trị, Quận Bình Thạnh, TP.HCM',
                latitude: 10.8168,
                longitude: 106.7213,
                estimatedArrivalTime: '2025-04-25T09:15:00',
                actualArrivalTime: null,
                status: 'PENDING',
                notes: '',
            },
            {
                id: 15,
                routeId: 3,
                orderId: 16,
                orderNumber: 'ORD-2025-0016',
                stopNumber: 3,
                address: '789 Bạch Đằng, Quận Bình Thạnh, TP.HCM',
                latitude: 10.8268,
                longitude: 106.7313,
                estimatedArrivalTime: '2025-04-25T10:00:00',
                actualArrivalTime: null,
                status: 'PENDING',
                notes: '',
            },
            {
                id: 16,
                routeId: 3,
                orderId: 17,
                orderNumber: 'ORD-2025-0017',
                stopNumber: 4,
                address: '101 Điện Biên Phủ, Quận Bình Thạnh, TP.HCM',
                latitude: 10.8368,
                longitude: 106.7413,
                estimatedArrivalTime: '2025-04-25T10:45:00',
                actualArrivalTime: null,
                status: 'PENDING',
                notes: '',
            },
            {
                id: 17,
                routeId: 3,
                orderId: 18,
                orderNumber: 'ORD-2025-0018',
                stopNumber: 5,
                address: '202 Nguyễn Hữu Cảnh, Quận Bình Thạnh, TP.HCM',
                latitude: 10.7868,
                longitude: 106.7113,
                estimatedArrivalTime: '2025-04-25T11:30:00',
                actualArrivalTime: null,
                status: 'PENDING',
                notes: '',
            },
        ],
    },
    {
        id: 4,
        name: 'Route #R2025-0048',
        startLocationId: 4,
        startLocationName: 'Kho Bình Dương',
        endLocationId: null,
        endLocationName: 'Thủ Dầu Một, Bình Dương',
        estimatedDistance: 22.7,
        estimatedDuration: 75,
        status: 'PLANNED',
        createdAt: '2025-04-23T18:15:00',
        scheduledDate: '2025-04-25',
        driverId: null,
        driverName: null,
        vehicleId: null,
        vehiclePlate: null,
        stops: [
            {
                id: 18,
                routeId: 4,
                orderId: 19,
                orderNumber: 'ORD-2025-0019',
                stopNumber: 1,
                address: '123 Đại lộ Bình Dương, Thủ Dầu Một, Bình Dương',
                latitude: 10.9804,
                longitude: 106.6521,
                estimatedArrivalTime: '2025-04-25T08:30:00',
                actualArrivalTime: null,
                status: 'PENDING',
                notes: '',
            },
            {
                id: 19,
                routeId: 4,
                orderId: 20,
                orderNumber: 'ORD-2025-0020',
                stopNumber: 2,
                address: '456 Phú Lợi, Thủ Dầu Một, Bình Dương',
                latitude: 10.9904,
                longitude: 106.6621,
                estimatedArrivalTime: '2025-04-25T09:30:00',
                actualArrivalTime: null,
                status: 'PENDING',
                notes: '',
            },
            {
                id: 20,
                routeId: 4,
                orderId: 21,
                orderNumber: 'ORD-2025-0021',
                stopNumber: 3,
                address: '789 Cách Mạng Tháng Tám, Thủ Dầu Một, Bình Dương',
                latitude: 11.0004,
                longitude: 106.6721,
                estimatedArrivalTime: '2025-04-25T10:30:00',
                actualArrivalTime: null,
                status: 'PENDING',
                notes: '',
            },
            {
                id: 21,
                routeId: 4,
                orderId: 22,
                orderNumber: 'ORD-2025-0022',
                stopNumber: 4,
                address: '101 Lê Hồng Phong, Thủ Dầu Một, Bình Dương',
                latitude: 11.0104,
                longitude: 106.6821,
                estimatedArrivalTime: '2025-04-25T11:30:00',
                actualArrivalTime: null,
                status: 'PENDING',
                notes: '',
            },
        ],
    },
    {
        id: 5,
        name: 'Route #R2025-0044',
        startLocationId: 1,
        startLocationName: 'Kho Quận 7',
        endLocationId: null,
        endLocationName: 'Quận 8, TP.HCM',
        estimatedDistance: 14.8,
        estimatedDuration: 50,
        status: 'COMPLETED',
        createdAt: '2025-04-22T17:00:00',
        scheduledDate: '2025-04-23',
        driverId: 1,
        driverName: 'Hoàng Minh Tuấn',
        vehicleId: 1,
        vehiclePlate: '51F-12345',
        stops: [
            {
                id: 22,
                routeId: 5,
                orderId: 23,
                orderNumber: 'ORD-2025-0023',
                stopNumber: 1,
                address: '123 Phạm Thế Hiển, Quận 8, TP.HCM',
                latitude: 10.7469,
                longitude: 106.6819,
                estimatedArrivalTime: '2025-04-23T08:30:00',
                actualArrivalTime: '2025-04-23T08:35:00',
                status: 'COMPLETED',
                notes: 'Đã giao hàng thành công',
            },
            {
                id: 23,
                routeId: 5,
                orderId: 24,
                orderNumber: 'ORD-2025-0024',
                stopNumber: 2,
                address: '456 Châu Văn Liêm, Quận 8, TP.HCM',
                latitude: 10.7569,
                longitude: 106.6919,
                estimatedArrivalTime: '2025-04-23T09:15:00',
                actualArrivalTime: '2025-04-23T09:20:00',
                status: 'COMPLETED',
                notes: 'Đã giao hàng thành công',
            },
            {
                id: 24,
                routeId: 5,
                orderId: 25,
                orderNumber: 'ORD-2025-0025',
                stopNumber: 3,
                address: '789 Hưng Phú, Quận 8, TP.HCM',
                latitude: 10.7669,
                longitude: 106.7019,
                estimatedArrivalTime: '2025-04-23T10:00:00',
                actualArrivalTime: '2025-04-23T10:10:00',
                status: 'COMPLETED',
                notes: 'Đã giao hàng thành công',
            },
            {
                id: 25,
                routeId: 5,
                orderId: 26,
                orderNumber: 'ORD-2025-0026',
                stopNumber: 4,
                address: '101 Dương Bá Trạc, Quận 8, TP.HCM',
                latitude: 10.7769,
                longitude: 106.7119,
                estimatedArrivalTime: '2025-04-23T10:45:00',
                actualArrivalTime: '2025-04-23T10:55:00',
                status: 'COMPLETED',
                notes: 'Đã giao hàng thành công',
            },
        ],
    },
];

export default routes;