server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - JwtAuthFilter
        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/drivers/**
          filters:
            - JwtAuthFilter
        - id: tracking-service
          uri: lb://tracking-service
          predicates:
            - Path=/tracking/**
          filters:
            - JwtAuthFilter
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
          filters:
            - JwtAuthFilter
        - id: reporting-service
          uri: lb://reporting-service
          predicates:
            - Path=/reports/**
          filters:
            - JwtAuthFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
